# Default training configuration
# Suitable for most sklearn and statistical models

max_epochs: 1  # Single training pass for sklearn models
early_stopping: false  # Not applicable for sklearn
patience: 10  # Not used but kept for compatibility
min_delta: 0.0001  # Minimum improvement threshold
monitor_metric: val_loss  # Metric to monitor
verbose: true  # Print training progress
save_checkpoints: true  # Save model checkpoints
checkpoint_dir: models/checkpoints  # Directory for saving checkpoints