[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "ml-portfolio"
version = "0.0.0"  # Placeholder - Poetry will manage versioning via git tags
description = "ML Portfolio - Time Series Forecasting Library"
authors = ["ML Portfolio <contact@ml-portfolio.com>"]
readme = "README.md"
license = "MIT"
packages = [{include = "ml_portfolio", from = "src"}]

[tool.poetry.dependencies]
python = ">=3.9,<3.13"
numpy = "*"
pandas = "*"
scikit-learn = "*"
matplotlib = "*"
hydra-core = "*"
omegaconf = "*"

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
pytest = "*"
black = "*"
ruff = "*"

[tool.poetry.group.train]
optional = true

[tool.poetry.group.train.dependencies]
optuna = "*"

[tool.poetry.extras]
statistical = ["statsmodels"]
deep_learning = ["torch"]
all = ["statsmodels", "torch", "optuna"]

[tool.black]
line-length = 120
target-version = ['py39', 'py310', 'py311']

[tool.ruff]
line-length = 120
target-version = "py39"

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = "test_*.py"
python_classes = "Test*"
python_functions = "test_*"
