[project]
name = "forecasting-demo"
version = "0.1.0"
description = "ml forecasting"
authors = [
    {name = "m villerabel"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "numpy>=1.21.0",
    "pandas>=1.5.0",
    "scikit-learn>=1.0.0",
    "matplotlib>=3.5.0",
    "hydra-core>=1.3.0",
    "omegaconf>=2.3.0",
]

# Optional extras for specific functionality
[project.optional-dependencies]
statistical = [
    "statsmodels>=0.13.0",
    "prophet>=1.1.0",
]
deep_learning = [
    "torch>=1.11.0",
]
optimization = [
    "optuna>=3.4.0",
]
dev = [
    "pytest>=7.0.0",
    "ruff>=0.1.0",
    "black>=22.0.0",
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

# Specify package location since it's in src/ directory
[tool.poetry]
packages = [{include = "ml_portfolio", from = "src"}]

# Tool configurations
[tool.black]
line-length = 120
target-version = ['py311']

[tool.ruff]
line-length = 120
target-version = "py311"

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = "test_*.py"
python_classes = "Test*"
python_functions = "test_*"
