# @package _global_

# LSTM Model Configuration
# Deep learning time series model
# Dataloader, engine, optimizer, and scheduler specified via defaults

defaults:
  - /dataloader: pytorch
  - /engine: pytorch
  - /optimizer: adam
  - /scheduler: cosine

model:
  # Model instantiation
  _target_: ml_portfolio.models.deep_learning.lstm.LSTMForecaster

  # LSTM architecture
  input_size: 1  # Will be set based on dataset
  hidden_size: 128
  num_layers: 2
  dropout: 0.2
  bidirectional: false

  # Output
  output_size: 1  # Forecast horizon

  # Training (will be used by engine)
  learning_rate: 0.001
