# LSTM model configuration (PyTorch)
# Use with dataloader=pytorch and training.max_epochs>1
# Note: input_size will be automatically set from dataset n_features

_target_: ml_portfolio.models.deep_learning.lstm.LSTMForecaster

# Architecture
input_size: 1  # Placeholder - will be overridden by dataset n_features
hidden_size: 128
num_layers: 2
dropout: 0.2

# Output
output_size: 1  # Forecast horizon

# Training parameters
lr: 0.001
epochs: 100
batch_size: 64
