# Pure ETS (Exponential Smoothing)
# Holt-Winters family models as standalone components

_target_: ml_portfolio.models.statistical.walmart_ensemble.WalmartEnsembleForecaster

# ETS-only configuration
models:
  - ets             # Pure exponential smoothing

# ETS will auto-select best configuration (Add/Mult trends/seasonality)
seasonal_period: 52
ensemble_method: "equal_weight"  # Not used for single model
enable_calendar_adjustment: true

# Model metadata
name: "pure_ets"
description: "Pure Exponential Smoothing (Holt-Winters family) forecaster"
citation: "Strong standalone component shared by top M5 competitors"
