# Random Forest model configuration (sklearn)
# Use with SimpleDataLoader and max_epochs=1

_target_: sklearn.ensemble.RandomForestRegressor

# Model parameters
n_estimators: 100
max_depth: 10
min_samples_split: 5
min_samples_leaf: 2
max_features: sqrt
random_state: 42

# Performance
n_jobs: -1  # Use all CPU cores
verbose: 0
