# @package _global_

# Random Forest Model Configuration
# Wrapped sklearn ensemble model for forecasting
# Dataloader and engine specified via defaults

defaults:
  - /dataloader: simple
  - /engine: statistical

model:
  # Model instantiation
  _target_: ml_portfolio.models.statistical.random_forest.RandomForestForecaster

  # Random Forest parameters
  n_estimators: 100
  max_depth: 10
  min_samples_split: 2
  min_samples_leaf: 1
  max_features: 1.0  # Changed from 'sqrt' to float for Optuna compatibility
  bootstrap: true
  random_state: 42
  n_jobs: -1
  verbose: 0
