# Seasonal Naive with Enhancements
# Year-ago same week with trend tweaks (3rd place M5 approach)

_target_: ml_portfolio.models.statistical.seasonal_naive.SeasonalNaiveForecaster

# Standard parameters
seasonal_period: 52
enable_calendar_adjustment: true  # Critical for seasonal naive performance

# Model metadata
# name: "enhanced_seasonal_naive"
# description: "Seasonal naive with calendar adjustments - remarkably strong baseline"
# citation: "3rd place M5 entry: year-ago/2-years-ago seasonal naive with week-blending"
# performance_note: "Surprisingly competitive against complex methods"
