# SVD + ETS Forecasting Model
# Cross-series pattern sharing with ETS forecasting

_target_: ml_portfolio.models.statistical.svd_models.SVDETSForecaster

# SVD parameters
n_components: 10                      # Number of SVD components to retain
standardize: true                     # Standardize series before SVD

# ETS parameters
seasonal_period: 52                   # Seasonal period for ETS models
ets_auto_select: true                 # Auto-select best ETS configuration

# Model metadata (comments only - not passed to constructor)
# name: "svd_ets"
# description: "SVD cross-series pattern sharing with ETS forecasting"
# citation: "Best single model from M5 winner - SVD + ETS approach"
# use_case: "Multi-series forecasting with pattern sharing across stores/departments"
