# SVD + ETS/STLF Forecasting
# Singular Value Decomposition across stores + STL-based forecasting with ETS

_target_: ml_portfolio.models.statistical.walmart_ensemble.WalmartEnsembleForecaster

# Focus on SVD-based models
models:
  - svd_ets       # SVD + ETS (best single model from M5)
  - stlf_arima    # STL + ARIMA combination

# SVD parameters
n_svd_components: 15     # More components for better cross-series pattern capture
seasonal_period: 52

# Ensemble settings
ensemble_method: "equal_weight"
enable_calendar_adjustment: true

# Model metadata
name: "svd_stlf_forecaster"
description: "SVD cross-series patterns with STL decomposition forecasting"
citation: "Best single model from M5 winner - SVD + STLF/ETS approach"
