# @package _global_

# Voting Ensemble Configuration
# Combines multiple models via averaging or weighted voting
# Dataloader and engine specified via defaults

defaults:
  - /dataloader: simple
  - /engine: statistical

model:
  _target_: ml_portfolio.models.ensemble.voting.VotingForecaster

  # Models (list of (name, model) tuples)
  models:
    - - lightgbm
      - _target_: ml_portfolio.models.statistical.lightgbm.LightGBMForecaster
        n_estimators: 100
        learning_rate: 0.1
        max_depth: 5

    - - xgboost
      - _target_: ml_portfolio.models.statistical.xgboost.XGBoostForecaster
        n_estimators: 100
        learning_rate: 0.1
        max_depth: 5

    - - catboost
      - _target_: ml_portfolio.models.statistical.catboost.CatBoostForecaster
        iterations: 100
        learning_rate: 0.1
        depth: 5

  # Voting configuration
  weights: null  # null for uniform, or [0.4, 0.3, 0.3] for weighted
  voting_type: mean  # 'mean' or 'median'

# Optuna hyperparameter search space
optuna:
  # Model combinations (categorical)
  model_combinations:
    - [prophet, lightgbm]
    - [prophet, xgboost]
    - [lightgbm, xgboost]
    - [prophet, lightgbm, xgboost]
    - [lightgbm, xgboost, catboost]
    - [prophet, lightgbm, xgboost, catboost]

  # Voting type
  voting_types: [mean, median]

  # Weight optimization (if not uniform)
  optimize_weights: true
  weight_resolution: 0.05  # Discretization step

  # Individual model hyperparameters
  prophet_growth: [linear, logistic]
  prophet_seasonality: [additive, multiplicative]

  lgbm_n_estimators_min: 50
  lgbm_n_estimators_max: 200
  lgbm_learning_rate_min: 0.01
  lgbm_learning_rate_max: 0.3

  xgb_n_estimators_min: 50
  xgb_n_estimators_max: 200
  xgb_learning_rate_min: 0.01
  xgb_learning_rate_max: 0.3

# Model metadata
metadata:
  family: ensemble
  type: voting
  requires_base_models: true
  meta_learning: false
  interpretable: true  # Simple averaging
  good_for:
    - quick_ensembles
    - robust_predictions
    - diverse_model_types
    - interpretability
