# @package _global_

# XGBoost Model Configuration
# Gradient boosting for time series forecasting
# Kaggle competition winner - robust and regularized

defaults:
  - /dataloader: simple
  - /engine: statistical

model:
  # Model instantiation
  _target_: ml_portfolio.models.statistical.xgboost.XGBoostForecaster

  # Core parameters
  n_estimators: 500
  learning_rate: 0.05
  max_depth: 8
  min_child_weight: 3.0

  # Sampling
  subsample: 0.8
  colsample_bytree: 0.8

  # Regularization
  gamma: 0.1  # Minimum loss reduction
  reg_alpha: 0.1  # L1 regularization
  reg_lambda: 1.0  # L2 regularization

  # Tree construction
  tree_method: hist  # 'auto', 'exact', 'approx', 'hist', 'gpu_hist'

  # Performance
  n_jobs: -1  # Use all CPU cores
  random_state: 42
  verbosity: 0  # 0=silent, 1=warning, 2=info, 3=debug

  # Early stopping (configured with validation set)
  early_stopping_rounds: 50
