"""
Utility functions and classes for the ML portfolio.
"""

from .io import (
    ensure_dir,
    load_csv,
    save_csv,
    load_parquet,
    save_parquet,
    load_pickle,
    save_pickle,
    load_json,
    save_json,
    DataCache,
    get_project_root,
    get_data_path,
    list_data_files,
    create_file_hash,
    CachedDataLoader,
)

from .config import (
    DatasetConfig,
    ModelConfig,
    OptimizerConfig,
    SchedulerConfig,
    TrainingConfig,
    ExperimentConfig,
    load_config,
    save_config,
    merge_configs,
    create_default_config,
    config_to_dict,
    dict_to_config,
    validate_config,
    setup_hydra_config,
    get_config_value,
    set_config_value,
    create_config_from_args,
    ConfigManager,
)

__all__ = [
    # I/O utilities
    "ensure_dir",
    "load_csv",
    "save_csv",
    "load_parquet",
    "save_parquet",
    "load_pickle",
    "save_pickle",
    "load_json",
    "save_json",
    "DataCache",
    "get_project_root",
    "get_data_path",
    "list_data_files",
    "create_file_hash",
    "CachedDataLoader",
    # Configuration
    "DatasetConfig",
    "ModelConfig",
    "OptimizerConfig",
    "SchedulerConfig",
    "TrainingConfig",
    "ExperimentConfig",
    "load_config",
    "save_config",
    "merge_configs",
    "create_default_config",
    "config_to_dict",
    "dict_to_config",
    "validate_config",
    "setup_hydra_config",
    "get_config_value",
    "set_config_value",
    "create_config_from_args",
    "ConfigManager",
]
