# Gradient Boosting model configuration

_target_: sklearn.ensemble.GradientBoostingRegressor

# Model hyperparameters
n_estimators: 100
learning_rate: 0.1
max_depth: 6
min_samples_split: 5
min_samples_leaf: 2
subsample: 1.0
max_features: null

# Randomness control
random_state: 42

# Advanced settings
loss: "squared_error"
alpha: 0.9
warm_start: false
validation_fraction: 0.1
n_iter_no_change: null
tol: 1e-4