# LSTM model configuration

_target_: ml_portfolio.models.deep_learning.lstm.LSTMForecaster

# Model architecture
input_size: 1
hidden_size: 64
num_layers: 2
output_size: 4  # 4-week forecast horizon
dropout: 0.2