# Random Forest model configuration for Walmart forecasting

_target_: sklearn.ensemble.RandomForestRegressor

# Model hyperparameters
n_estimators: 100
max_depth: 15
min_samples_split: 5
min_samples_leaf: 2
max_features: "sqrt"
bootstrap: true

# Randomness control
random_state: 42
n_jobs: -1

# Model-specific settings
criterion: "squared_error"
max_samples: null
warm_start: false