# Ridge Regression model configuration

_target_: sklearn.linear_model.Ridge

# Model hyperparameters
alpha: 1.0
fit_intercept: true
copy_X: true
max_iter: null
tol: 1e-4
solver: "auto"
positive: false
random_state: 42