# Optuna hyperparameter optimization configuration
# This config enables hyperparameter tuning using Optuna

# Basic study configuration
study_name: ${model._target_}_${dataset_factory._target_}_${now:%Y%m%d_%H%M%S}
storage: sqlite:///optuna_studies.db
direction: minimize  # or maximize depending on metric
n_trials: 100
timeout: null  # seconds, null for no timeout

# Optimization settings
sampler:
  _target_: optuna.samplers.TPESampler
  n_startup_trials: 10
  n_ei_candidates: 24
  seed: 42

pruner:
  _target_: optuna.pruners.MedianPruner
  n_startup_trials: 5
  n_warmup_steps: 10
  interval_steps: 1

# Metric to optimize (should match primary metric in metrics config)
optimize_metric: ${metrics.primary_metric}  # e.g., mae, rmse, mape
minimize_metric: ${metrics.minimize}  # true or false

# MLflow integration
log_to_mlflow: true
mlflow_experiment_suffix: _optuna

# Parallel execution
n_jobs: 1  # number of parallel trials (set to -1 for all CPU cores)

# Early stopping for trials
enable_pruning: true
