# Optuna hyperparameter optimization configuration for TCN
# Search space for Temporal Convolutional Network

sampler:
  _target_: optuna.samplers.TPESampler
  seed: 42
  n_startup_trials: 10

pruner:
  _target_: optuna.pruners.MedianPruner
  n_startup_trials: 5
  n_warmup_steps: 10

search_space:
  # TCN architecture
  model.num_channels:
    type: categorical
    choices:
      - [32, 64, 128]
      - [64, 128, 256]
      - [32, 64, 128, 256]

  model.kernel_size:
    type: categorical
    choices: [3, 5, 7]

  model.dropout:
    type: float
    low: 0.0
    high: 0.5
    step: 0.1

  # Training hyperparameters
  model.learning_rate:
    type: loguniform
    low: 0.0001
    high: 0.01

  engine.epochs:
    type: categorical
    choices: [50, 100, 150, 200]

  # Optimizer
  optimizer.weight_decay:
    type: loguniform
    low: 0.00001
    high: 0.001

  # Data processing
  dataloader.batch_size:
    type: categorical
    choices: [16, 32, 64, 128]

  dataloader.window_size:
    type: int
    low: 7
    high: 30
    step: 7

  dataloader.forecast_horizon:
    type: int
    low: 1
    high: 14

# Optimization direction
direction: minimize

# Metric to optimize
metric: val_MAPE
