# Full Feature Engineering with Multiple Transformers
#
# Demonstrates multiple preprocessing steps in StatisticalPreprocessingPipeline

# ============================================================================
# STATIC FEATURE ENGINEERING (Applied BEFORE splitting)
# ============================================================================
static:
  _target_: ml_portfolio.data.preprocessing.StaticTimeSeriesPreprocessingPipeline

  date_column: date
  group_columns: null
  target_column: target

  lag_features:
    - 1
    - 7
    - 14
    - 28

  rolling_windows:
    - 7
    - 14
    - 30

  date_features: true

  cyclical_features:
    - month
    - dayofweek
    - quarter

# ============================================================================
# STATISTICAL PREPROCESSING (Applied AFTER splitting, fit on train)
# ============================================================================
statistical:
  _target_: ml_portfolio.data.preprocessing.StatisticalPreprocessingPipeline

  steps:
    # Remove outliers with RobustScaler
    - - robust_scaler
      - _target_: sklearn.preprocessing.RobustScaler
        with_centering: true
        with_scaling: true
        quantile_range: [5.0, 95.0]

    # Then standardize with StandardScaler
    - - feature_scaler
      - _target_: sklearn.preprocessing.StandardScaler
        with_mean: true
        with_std: true

    # Scale target separately
    - - target_scaler
      - _target_: sklearn.preprocessing.StandardScaler
        with_mean: true
        with_std: true
