# Minimal Feature Engineering
#
# Minimal static features + standard scaling

# ============================================================================
# STATIC FEATURE ENGINEERING (Applied BEFORE splitting)
# ============================================================================
static:
  _target_: ml_portfolio.data.preprocessing.StaticTimeSeriesPreprocessingPipeline

  date_column: date
  group_columns: null
  target_column: target

  lag_features: []  # No lags
  rolling_windows: []  # No rolling windows
  date_features: true  # Only date features

  cyclical_features:
    - month
    - dayofweek

# ============================================================================
# STATISTICAL PREPROCESSING (Applied AFTER splitting, fit on train)
# ============================================================================
statistical:
  _target_: ml_portfolio.data.preprocessing.StatisticalPreprocessingPipeline

  steps:
    - - feature_scaler
      - _target_: sklearn.preprocessing.StandardScaler
        with_mean: true
        with_std: true
