# Statistical Preprocessing Only
#
# Only StatisticalPreprocessingPipeline (applied AFTER splitting)
# No static feature engineering

# ============================================================================
# STATIC FEATURE ENGINEERING (Applied BEFORE splitting)
# ============================================================================
static: null  # No static feature engineering

# ============================================================================
# STATISTICAL PREPROCESSING (Applied AFTER splitting, fit on train)
# ============================================================================
statistical:
  _target_: ml_portfolio.data.preprocessing.StatisticalPreprocessingPipeline

  steps:
    - - feature_scaler
      - _target_: sklearn.preprocessing.StandardScaler
        with_mean: true
        with_std: true

    - - target_scaler
      - _target_: sklearn.preprocessing.StandardScaler
        with_mean: true
        with_std: true
