# Walmart Full Feature Engineering Pipeline
#
# Combines both:
# 1. StaticTimeSeriesPreprocessingPipeline (applied BEFORE splitting)
# 2. StatisticalPreprocessingPipeline (applied AFTER splitting, fit on train)
#
# Tailored for Walmart dataset with Weekly_Sales as target

# ============================================================================
# STATIC FEATURE ENGINEERING (Applied BEFORE splitting)
# ============================================================================
static:
  _target_: ml_portfolio.data.preprocessing.StaticTimeSeriesPreprocessingPipeline

  # Column names (must match Walmart dataset)
  date_column: Date
  group_columns: [Store]  # Group by Store for store-specific features
  target_column: Weekly_Sales

  # Lag features (backward-looking, safe)
  # Weekly data - use weekly lags
  lag_features:
    - 1   # Previous week
    - 2   # 2 weeks ago
    - 4   # 1 month ago
    - 8   # 2 months ago
    - 13  # Quarter ago
    - 26  # Half year ago
    - 52  # Year ago (seasonal)

  # Rolling window features (backward-looking with shift, safe)
  # Calculate rolling statistics
  rolling_windows:
    - 4   # 1 month rolling
    - 8   # 2 months rolling
    - 13  # Quarter rolling
    - 26  # Half year rolling
    - 52  # Year rolling

  # Date features (deterministic, safe)
  date_features: true

  # Cyclical encoding for periodic features (deterministic, safe)
  # Important for weekly seasonality and yearly patterns
  cyclical_features:
    - month        # Monthly seasonality
    - dayofweek    # Day of week patterns
    - quarter      # Quarterly patterns
    - week         # Week of year (52 weeks)

# ============================================================================
# STATISTICAL PREPROCESSING (Applied AFTER splitting, fit on train)
# ============================================================================
statistical:
  _target_: ml_portfolio.data.preprocessing.StatisticalPreprocessingPipeline

  steps:
    # Scale features using StandardScaler
    - - feature_scaler
      - _target_: sklearn.preprocessing.StandardScaler
        with_mean: true
        with_std: true

    # Scale target separately (for better model performance)
    - - target_scaler
      - _target_: sklearn.preprocessing.StandardScaler
        with_mean: true
        with_std: true

# Note:
# - Weekly_Sales ranges widely (can be millions), so scaling is important
# - Store-specific lags and rolling windows capture store-level patterns
# - Seasonal features (week, month, quarter) capture yearly patterns
# - Holiday_Flag, Temperature, Fuel_Price, CPI, Unemployment are already in the data
# - Steps with names starting with "target_" are applied to y
# - All other steps are applied to X
