# Main configuration for retail_sales_walmart
# This file defines default settings for all experiments

defaults:
  - dataset: walmart_custom
  - model: random_forest
  - optimizer: adam
  - scheduler: cosine
  - _self_

# Experiment settings
experiment:
  name: retail_sales_walmart_baseline
  tags: [baseline, walmart]

# Training settings  
trainer:
  max_epochs: 100
  patience: 10
  
# Evaluation settings
evaluation:
  primary_metric: WMAE
  cv_folds: 5
