# Walmart Sales Forecasting Configuration
# Simplified configuration for basic forecasting models

defaults:
  # Import local Walmart dataset config
  - dataset: walmart
  - _self_

# Simple dataloader for sklearn models (no batching needed)
dataloader:
  _target_: ml_portfolio.data.loaders.SimpleDataLoader
  batch_size: ${dataset.batch_size}
  shuffle: false

# Model configuration (can be overridden via command line)
model:
  _target_: sklearn.ensemble.RandomForestRegressor
  n_estimators: 100
  max_depth: 10
  min_samples_split: 5
  min_samples_leaf: 2
  random_state: 42
  n_jobs: -1

# Dataset configuration
dataset:
  data_path: data/raw/Walmart.csv
  lookback_window: 52  # Weekly data, look back 1 year
  forecast_horizon: 12  # Forecast 12 weeks ahead (3 months)
  batch_size: 64
  
  # Walmart-specific features
  include_store_features: true
  include_dept_features: true
  include_holiday_features: true
  
  # Data splitting (temporal)
  train_ratio: 0.7
  validation_ratio: 0.15
  test_ratio: 0.15
  
  # Feature engineering
  scale_features: true
  scale_target: true
  scaler_type: standard

# Training configuration
trainer:
  max_epochs: 1  # sklearn trains in one shot
  patience: 10
  early_stopping: false  # Not applicable for sklearn
  verbose: true
  save_checkpoints: true
  checkpoint_dir: models/checkpoints
  monitor_metric: val_wmape
  
# Metrics configuration
metrics:
  mae:
    _target_: sklearn.metrics.mean_absolute_error
  rmse:
    _target_: sklearn.metrics.mean_squared_error
    squared: false
  mape:
    _target_: sklearn.metrics.mean_absolute_percentage_error
  r2:
    _target_: sklearn.metrics.r2_score

# Primary metric for optimization (Walmart-specific)
primary_metric: mape

# Experiment settings
experiment:
  name: retail_sales_walmart_baseline
  tags: [baseline, walmart]

# Random seed for reproducibility
seed: 42

# Hydra configuration
hydra:
  run:
    dir: outputs/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: multirun/${now:%Y-%m-%d_%H-%M-%S}
    subdir: ${hydra.job.num}
  job:
    chdir: false
