# MLflow configuration for production experiments
tracking_uri: "file://./mlruns"  # Local file-based tracking
experiment_name: "production_forecasting"
run_name: null
enable_auto_logging: true
log_params: true
log_metrics: true
log_artifacts: true
log_model: true

artifact_location: "./mlruns"
log_predictions: true
log_feature_importance: true
log_plots: true

register_model: true
model_name: null

tags:
  team: "ml_portfolio"
  environment: "production"
  framework: "hydra"

auto_log_frameworks:
  sklearn: true
  pytorch: true
  statsmodels: false
