# Default Dataset Factory Configuration
# Creates train/val/test dataset splits from raw data
# Static feature engineering happens BEFORE splitting (safe, deterministic)
# Statistical preprocessing happens AFTER splitting (fit on train)

_target_: ml_portfolio.data.dataset_factory.DatasetFactory

# Data source
data_path: data/processed/data.csv  # Path to data file (CSV or Parquet)

# Column specifications
target_column: target  # Name of target column
feature_columns: null  # List of feature columns, null = all except target
timestamp_column: null  # Optional timestamp column for time series

# Split ratios (must sum to 1.0)
train_ratio: 0.7
val_ratio: 0.15
test_ratio: 0.15

# Static feature engineering (applied BEFORE splitting)
# This is passed from cfg.feature_engineering.static in train.py
static_feature_engineer: ${feature_engineering.static}

# Note:
# - Static features are applied BEFORE splitting (safe, no leakage)
# - Statistical preprocessing happens AFTER splitting using StatisticalPreprocessingPipeline
