# Test configuration for Optuna integration
# Usage: python src/ml_portfolio/training/train.py --config-name config_optuna_test --multirun

defaults:
  - walmart  # Inherit from walmart.yaml
  - override hydra/sweeper: optuna
  - _self_

# Enable MLflow and Optuna
use_mlflow: true
use_optuna: true
experiment_name: optuna_test
dataset_name: Walmart_Sales

# Hydra Optuna sweeper configuration
hydra:
  sweeper:
    _target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper

    # Optimization settings
    direction: minimize  # Minimize val_MAPE
    n_trials: 10  # Small number for testing
    n_jobs: 1

    # Sampler configuration
    sampler:
      _target_: optuna.samplers.TPESampler
      seed: 42
      n_startup_trials: 3
      multivariate: true

    # Pruner for early stopping of bad trials
    pruner:
      _target_: optuna.pruners.MedianPruner
      n_startup_trials: 3
      n_warmup_steps: 0
      interval_steps: 1

    # Search space definition
    params:
      # Model selection
      model: choice(lightgbm, xgboost, random_forest)

      # LightGBM/XGBoost hyperparameters
      +model.n_estimators: choice(50, 100, 200)
      +model.max_depth: range(3, 8)
      +model.learning_rate: interval(0.01, 0.2)

# Optimization settings
primary_metric: MAPE  # Which metric to optimize (always from validation set)
minimize: true  # Minimize the metric (set to false for metrics like accuracy)
