# Main configuration for rideshare_demand_ola
# This file defines default settings for all experiments

defaults:
  - dataset: ola
  - model: lstm
  - optimizer: adam
  - scheduler: cosine
  - _self_

# Experiment settings
experiment:
  name: rideshare_demand_ola_baseline
  tags: [baseline, ola]

# Training settings  
trainer:
  max_epochs: 100
  patience: 10
  
# Evaluation settings
evaluation:
  primary_metric: MAPE
  cv_folds: 5
