# SimpleDataLoader configuration
# Returns all data in single batch (infinite batch size)
# Perfect for sklearn models that expect fit(X, y) with complete dataset

_target_: ml_portfolio.data.loaders.SimpleDataLoader
shuffle: true  # Shuffle indices before creating batch

# Note: batch_size is ignored - always returns full dataset
# This loader yields exactly 1 batch containing all data
