# Default Metrics Configuration
# List of metrics to compute during training and evaluation

# Primary metric for model selection and early stopping
primary_metric: mape  # Options: mape, rmse, mae

# Whether to minimize the primary metric (true for error metrics, false for accuracy metrics)
minimize: true

# List of metrics to compute
# Each metric is instantiated as a class from ml_portfolio.evaluation.metrics
metrics:
  - _target_: ml_portfolio.evaluation.metrics.MAPEMetric
    name: mape
    epsilon: 1e-8

  - _target_: ml_portfolio.evaluation.metrics.RMSEMetric
    name: rmse

  - _target_: ml_portfolio.evaluation.metrics.MAEMetric
    name: mae

# Note: Each metric class has a __call__ method that takes (y_true, y_pred)
# The engine will instantiate these classes and call them as: metric_instance(y_true, y_pred)
