# Default metrics configuration
# Metrics to compute during training and evaluation

# Regression metrics (for forecasting) - structured as expected by TrainingEngine
mae:
  _target_: ml_portfolio.models.metrics.MAEMetric
  name: mae

rmse:
  _target_: ml_portfolio.models.metrics.RMSEMetric
  name: rmse

mape:
  _target_: ml_portfolio.models.metrics.MAPEMetric
  name: mape
  epsilon: 1e-8

# Primary metric for early stopping
primary_metric: mae
minimize: true  # true for loss metrics, false for accuracy metrics
