# Default Metrics Configuration
# List of metrics to compute during training and evaluation

# Primary metric for model selection and early stopping
primary_metric: mape  # Options: mape, rmse, mae

# Whether to minimize the primary metric (true for error metrics, false for accuracy metrics)
minimize: true

# List of metrics to compute
# Each metric should be a callable from ml_portfolio.evaluation.metrics
metrics:
  - _target_: ml_portfolio.evaluation.metrics.mape
    _partial_: true

  - _target_: ml_portfolio.evaluation.metrics.rmse
    _partial_: true

  - _target_: ml_portfolio.evaluation.metrics.mae
    _partial_: true

# Note: _partial_: true creates a partial function that will be called with (y_true, y_pred)
# The engine will iterate through this list and compute all metrics
